name: neptune
version: 0.1.0

author: Exora Project

executables:
  neptune:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -O2

dependencies:
  - base >= 4.7 && < 5
  - discord-haskell >= 1.15.5
  - postgresql-simple >= 0.7
  - hedis >= 0.15
  - bytestring
  - text
  - data-default
  - dotenv
